# Source file for libraries and functions used in the project


####--------------------------------------------####
## PACKAGES
####--------------------------------------------####

mylibraries <- c("sf", "raster", "tmap", "tmaptools","dismo", "tidyverse", "plotROC", "ROCR",
                 "sp", "adehabitatHR", "lubridate", "viridis", "ggrepel", "corrplot",
                 "reshape2", "fasterize", "parallel", "mgcv", "MuMIn", "lme4",
                 "ggeffects", "effects", "ecospat", "DHARMa", "biomod2", "scales",
                 "quickPlot", "RColorBrewer", "ggforce", "scatterpie", "ggExtra",
                 "rworldmap")

for (i in 1:length(mylibraries)) {
  if(mylibraries[i] %in% rownames(installed.packages()) == FALSE) {install.packages(mylibraries[i])}
}
lapply(mylibraries, require, character.only = TRUE)


####--------------------------------------------####
## FUNCTIONS
####--------------------------------------------####

## Mode
getmode <- function(v) {
  uniqv <- unique(v)
  uniqv[which.max(tabulate(match(v, uniqv)))]
}


## TSS test

# tss function
calc_tss <- function(samples, background, threshold){
  sensitivity <-sum( samples$predict >= threshold, na.rm = TRUE) /nrow( samples )
  specificity <-sum( background$predict < threshold, na.rm = TRUE) /nrow( background )
  sensitivity + specificity - 1
}

# maxent_out <- paste0(results_wd, "/maxent_mcp_results_test/")

# TSS for maxent replicates
get_maxent_tss <- function(model_directory, data.type = "test", n.replicates){
  ## Extrac MaxSSS threshold values from the maxent outputs
  # Load thresholds
  thresh_tmp <- read.csv(paste0(model_directory,"/maxentResults.csv"), header=TRUE)
  #Select only logistic threshold values and invert the table
  thresh_df <- thresh_tmp[,c(grep("Maximum.+logistic.threshold",names(thresh_tmp)))]
  thresh_df$run <- 1:nrow(thresh_df)
  thresh_df <-melt(thresh_df, id.vars=c("run"))
  thresh_df <- rename(thresh_df, threshold = variable)
  # Select the MaxSSS threshold
  # (Here, Maximum Test Sensitivity Plus Specificity; MaxSSS)
  #
  sub_thresh <- thresh_df[c(grep(paste0("Maximum.", data.type),thresh_df$threshold))[1:n.replicates], ] # ten values because the 11th is the average model
  sub_thresh <- data.frame(sub_thresh)

  ## Extract predictions from sample files
  # create empty vector
  s_samp_df <- list()
  # For-loop
  for (i in 1:n.replicates){
    #Read CSV file of maxent results (generated by maxent earlier)
    res_df <- read.csv(paste0(model_directory,"/species_", i-1, "_samplePredictions.csv"), header=TRUE)
    # remove training values
    res_df <- res_df[(res_df$Test.or.train == data.type),]
    #Select only logistic threshold values and invert the table
    # name here matches name in tss_calc function
    predict <- res_df[,c(grep("Logistic.prediction", names(res_df)))]
    # change to dataframe with column of number of run
    samp_df <- data.frame(run = i, predict)
    # Add to List
    s_samp_df[[i]] <- samp_df
  }
  samp_all <- do.call(rbind, s_samp_df)

  ## Extract predictions from background files
  # create empty vector
  s_bg_df <- list()
  # For-loop
  for (j in 1:n.replicates){
    #Read CSV file of maxent results (generated by maxent earlier)
    res_df <- read.csv(paste0(model_directory,"/species_", j-1, "_backgroundPredictions.csv"), header=TRUE)
    #Select only logistic prediction values
    # name here matches name in tss_calc function
    predict <- res_df[,c(grep("logistic", names(res_df)))]
    # Add a column to indicate corresponding run within the table
    bg_df <- data.frame(run = j, predict)
    # Add to List
    s_bg_df[[j]] <- bg_df
  }
  bg_all <- do.call(rbind, s_bg_df)

  ## Calculate TSS in a for-loop
  # empty list
  tss <- vector()

  # tss for-loop
  for (run in 1:n.replicates){
    # extract threshold by number in row
    threshold <- sub_thresh$value[run]
    # extract sample and background predictions by number of run
    samples <- samp_all[(samp_all$run==run),]
    background <- bg_all[(bg_all$run==paste0(run)),]
    # run tss function
    tss_run <- calc_tss(samples,background,threshold)
    # add to list
    tss[run] <- tss_run
  }

  final_data <- cbind.data.frame(sub_thresh, tss)
  return(final_data)
}



####--------------------------------------------####
####--------------------------------------------####




sessionInfo()
# R version 3.6.3 (2020-02-29)
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows 10 x64 (build 18363)
#
# Matrix products: default
#
# locale:
#   [1] LC_COLLATE=English_Ireland.1252  LC_CTYPE=English_Ireland.1252    LC_MONETARY=English_Ireland.1252
# [4] LC_NUMERIC=C                     LC_TIME=English_Ireland.1252
#
# attached base packages:
#   [1] parallel  stats     graphics  grDevices utils     datasets  methods   base
#
# other attached packages:
#   [1] biomod2_3.4.13      DHARMa_0.3.3.0      ecospat_3.2         gbm_2.1.8           ape_5.4-1           effects_4.2-0
# [7] carData_3.0-4       ggeffects_1.0.1     lme4_1.1-23         Matrix_1.2-18       MuMIn_1.43.17       mgcv_1.8-31
# [13] nlme_3.1-144        fasterize_1.0.3     reshape2_1.4.4      corrplot_0.84       ggrepel_0.9.1       viridis_0.5.1
# [19] viridisLite_0.3.0   lubridate_1.7.9     adehabitatHR_0.4.18 adehabitatLT_0.3.25 CircStats_0.2-6     boot_1.3-24
# [25] MASS_7.3-51.5       adehabitatMA_0.3.14 ade4_1.7-15         deldir_0.1-29       ROCR_1.0-11         plotROC_2.2.1
# [31] forcats_0.5.0       stringr_1.4.0       dplyr_1.0.2         purrr_0.3.4         readr_1.3.1         tidyr_1.1.2
# [37] tibble_3.0.3        ggplot2_3.3.2       tidyverse_1.3.0     dismo_1.1-4         tmap_3.2            raster_3.3-13
# [43] sp_1.4-2            sf_0.9-6
#
# loaded via a namespace (and not attached):
#   [1] ks_1.12.0             rms_6.1-1             tidyselect_1.1.0      htmlwidgets_1.5.1     grid_3.6.3
# [6] maptools_1.0-2        ecodist_2.0.7         pROC_1.16.2           devtools_2.3.1        munsell_0.5.0
# [11] codetools_0.2-16      units_0.6-7           statmod_1.4.34        withr_2.3.0           colorspace_1.4-1
# [16] knitr_1.30            rstudioapi_0.11       stats4_3.6.3          TeachingDemos_2.12    ENMeval_0.3.1
# [21] rprojroot_1.3-2       TH.data_1.0-10        vctrs_0.3.4           generics_0.1.0        ipred_0.9-9
# [26] xfun_0.17             randomForest_4.6-14   R6_2.4.1              doParallel_1.0.16     reshape_0.8.8
# [31] assertthat_0.2.1      scales_1.1.1          multcomp_1.4-16       nnet_7.3-12           gtable_0.3.0
# [36] lwgeom_0.2-5          conquer_1.0.2         processx_3.4.4        mda_0.5-2             sandwich_3.0-0
# [41] MatrixModels_0.4-1    timeDate_3043.102     rlang_0.4.7           splines_3.6.3         ModelMetrics_1.2.2.2
# [46] dichromat_2.0-0       hexbin_1.28.2         earth_5.3.0           broom_0.7.0           checkmate_2.0.0
# [51] yaml_2.2.1            abind_1.4-5           modelr_0.1.8          crosstalk_1.1.0.1     backports_1.1.10
# [56] Hmisc_4.5-0           caret_6.0-86          lava_1.6.8.1          tools_3.6.3           usethis_1.6.1
# [61] nabor_0.5.0           ellipsis_0.3.1        RColorBrewer_1.1-2    sessioninfo_1.1.1     Rcpp_1.0.5
# [66] plyr_1.8.6            base64enc_0.1-3       classInt_0.4-3        ps_1.3.4              prettyunits_1.1.1
# [71] rpart_4.1-15          tmaptools_3.1         zoo_1.8-8             cluster_2.1.0         haven_2.3.1
# [76] fs_1.5.0              survey_4.0            leafem_0.1.3          tinytex_0.26          magrittr_1.5
# [81] data.table_1.13.0     SparseM_1.78          reprex_0.3.0          mvtnorm_1.1-1         matrixStats_0.56.0
# [86] pkgload_1.1.0         hms_0.5.3             evaluate_0.14         XML_3.99-0.3          leaflet_2.0.3
# [91] jpeg_0.1-8.1          mclust_5.4.7          readxl_1.3.1          gridExtra_2.3         testthat_2.3.2
# [96] compiler_3.6.3        KernSmooth_2.23-16    crayon_1.3.4          minqa_1.2.4           htmltools_0.5.0
# [101] Formula_1.2-4         DBI_1.1.0             sjlabelled_1.1.7      dbplyr_1.4.4          permute_0.9-5
# [106] cli_2.0.2             mitools_2.4           gower_0.2.2           insight_0.13.1        pkgconfig_2.0.3
# [111] foreign_0.8-75        recipes_0.1.15        xml2_1.3.2            foreach_1.5.0         prodlim_2019.11.13
# [116] plotmo_3.6.0          rvest_0.3.6           callr_3.4.4           digest_0.6.25         vegan_2.5-6
# [121] rmarkdown_2.3         cellranger_1.1.0      htmlTable_2.1.0       leafsync_0.1.0        PresenceAbsence_1.1.9
# [126] curl_4.3              gtools_3.8.2          quantreg_5.61         nloptr_1.2.2.2        lifecycle_0.2.0
# [131] jsonlite_1.7.1        desc_1.2.0            fansi_0.4.1           pillar_1.4.6          lattice_0.20-41
# [136] httr_1.4.2            plotrix_3.8-1         pkgbuild_1.1.0        survival_3.2-7        glue_1.4.2
# [141] remotes_2.2.0         rasterVis_0.49        png_0.1-7             iterators_1.0.12      class_7.3-15
# [146] stringi_1.5.3         maxnet_0.1.2          blob_1.2.1            polspline_1.1.19      latticeExtra_0.6-29
# [151] stars_0.4-3           memoise_1.1.0         snowfall_1.84-6.1     poibin_1.5            e1071_1.7-3
